static const char *event_names[] =
{
    "Eevee Spotlight",
    "Charizard the Unrivaled",
    "Tyranitar and Salamence Spotlight",
    "Presents from Delibird",
    "Cinderace the Unrivaled",
    "Hydreigon and Dragapult Spotlight",
    "Drifblim and Mismagius Spotlight",
    "Greninja the Unrivaled",
    "Armarouge and Ceruledge Spotlight",
    "Happy Valentine's Day",
    "Garchomp and Sylveon Spotlight",
    "Pikachu the Unrivaled",
    "Walking Wake and Iron Leaves Spotlight",
    "Decidueye the Unrivaled",
    "Blissey Spotlight",
    "Samurott the Unrivaled",
    "Ditto Spotlight",
    "Typhlosion the Unrivaled",
    "Inteleon the Unrivaled",
    "Chesnaught the Unrivaled",
    "Great Tusk and Iron Treads Spotlight",
    "Gimmighoul Spotlight",
    "Delphox the Unrivaled",
    "Rillaboom the Unrivaled",
    "Prepare the Offense",
    "A Show of Supporters",
    "Mewtwo the Unrivaled",
    "Slither Wing and Iron Moth Spotlight",
    "Decidueye the Unrivaled (Hisuian)",
    "Mismagius Spotlight",
    "Typhlosion the Unrivaled (Hisuian)",
    "Eevee the Unrivaled",
    "Samurott the Unrivaled (Hisuian)",
    "Dialga and Palkia Spotlight",
    "Iron Bundle the Unrivaled",
    "Blaziken the Unrivaled",
    "Flutter Mane and Iron Jugulis Spotlight",
    "Empoleon the Unrivaled",
    "Valentines Day 2024",
    "Hard to Find Pokemon",
    "Venusaur the Unrivaled",
    "Blastoise the Unrivaled",
    "Charizard the Unrivaled (rerun)",
    "Brute Bonnet and Iron Hands Spotlight",
    "Meganium the Unrivaled",
    "Walking Wake and Iron Leaves Spotlight (rerun)",
    "Primarina the Unrivaled",
    "Sandy Shocks and Iron Thorns Spotlight",
    "Swampert the Unrivaled",
    "Emboar the Unrivaled",
    "Sceptile the Unrivaled",
    "Pikachu the Unrivaled (rerun)",
    "Dondozo the Unrivaled",
    "Gimmighoul Spotlight (rerun)",
    "Dragonite the Unrivaled",
    "Inceneroar the Unrivaled",
    "Serperior the Unrivaled",
    "Infernape the Unrivaled",
    "Hard to Find Pokemon (rerun)",
    "Gengar Spotlight",
    "Feraligatr the Unrivaled",
    "Torterra the Unrivaled",
    "Worthy Corviknight and Bellibolt",
    "Worthy Azumarill and Clodsire",
    "Worthy Annihilape and Kingambit",
    "Shiny Rayquaza Appears",
    "Alolan Exeggutor Spotlight",
    "Scream Tail and Iron Bundle Spotlight",
    "Milcery Spotlight",
    "Meowscarada the Unrivaled",
    "Skeledirge the Unrivaled",
    "Quaquaval the Unrivaled",
    "Tyranitar the Unrivaled",
    "Salamence the Unrivaled",
    "Metagross the Unrivaled",
};
