#pragma once

#include "EventNames.inc.h"

static const char* pokemon_names[] =
{
	"---",
	"Bulbasaur",
	"Ivysaur",
	"Venusaur",
	"Charmander",
	"Charmeleon",
	"Charizard",
	"Squirtle",
	"Wartortle",
	"Blastoise",
	"Caterpie",
	"Metapod",
	"Butterfree",
	"Weedle",
	"Kakuna",
	"Beedrill",
	"Pidgey",
	"Pidgeotto",
	"Pidgeot",
	"Rattata",
	"Raticate",
	"Spearow",
	"Fearow",
	"Ekans",
	"Arbok",
	"Pikachu",
	"Raichu",
	"Sandshrew",
	"Sandslash",
	"Nidoran(F)",
	"Nidorina",
	"Nidoqueen",
	"Nidoran(M)",
	"Nidorino",
	"Nidoking",
	"Clefairy",
	"Clefable",
	"Vulpix",
	"Ninetales",
	"Jigglypuff",
	"Wigglytuff",
	"Zubat",
	"Golbat",
	"Oddish",
	"Gloom",
	"Vileplume",
	"Paras",
	"Parasect",
	"Venonat",
	"Venomoth",
	"Diglett",
	"Dugtrio",
	"Meowth",
	"Persian",
	"Psyduck",
	"Golduck",
	"Mankey",
	"Primeape",
	"Growlithe",
	"Arcanine",
	"Poliwag",
	"Poliwhirl",
	"Poliwrath",
	"Abra",
	"Kadabra",
	"Alakazam",
	"Machop",
	"Machoke",
	"Machamp",
	"Bellsprout",
	"Weepinbell",
	"Victreebel",
	"Tentacool",
	"Tentacruel",
	"Geodude",
	"Graveler",
	"Golem",
	"Ponyta",
	"Rapidash",
	"Slowpoke",
	"Slowbro",
	"Magnemite",
	"Magneton",
	"Farfetch'd",
	"Doduo",
	"Dodrio",
	"Seel",
	"Dewgong",
	"Grimer",
	"Muk",
	"Shellder",
	"Cloyster",
	"Gastly",
	"Haunter",
	"Gengar",
	"Onix",
	"Drowzee",
	"Hypno",
	"Krabby",
	"Kingler",
	"Voltorb",
	"Electrode",
	"Exeggcute",
	"Exeggutor",
	"Cubone",
	"Marowak",
	"Hitmonlee",
	"Hitmonchan",
	"Lickitung",
	"Koffing",
	"Weezing",
	"Rhyhorn",
	"Rhydon",
	"Chansey",
	"Tangela",
	"Kangaskhan",
	"Horsea",
	"Seadra",
	"Goldeen",
	"Seaking",
	"Staryu",
	"Starmie",
	"Mr. Mime",
	"Scyther",
	"Jynx",
	"Electabuzz",
	"Magmar",
	"Pinsir",
	"Tauros",
	"Magikarp",
	"Gyarados",
	"Lapras",
	"Ditto",
	"Eevee",
	"Vaporeon",
	"Jolteon",
	"Flareon",
	"Porygon",
	"Omanyte",
	"Omastar",
	"Kabuto",
	"Kabutops",
	"Aerodactyl",
	"Snorlax",
	"Articuno",
	"Zapdos",
	"Moltres",
	"Dratini",
	"Dragonair",
	"Dragonite",
	"Mewtwo",
	"Mew",
	"Chikorita",
	"Bayleef",
	"Meganium",
	"Cyndaquil",
	"Quilava",
	"Typhlosion",
	"Totodile",
	"Croconaw",
	"Feraligatr",
	"Sentret",
	"Furret",
	"Hoothoot",
	"Noctowl",
	"Ledyba",
	"Ledian",
	"Spinarak",
	"Ariados",
	"Crobat",
	"Chinchou",
	"Lanturn",
	"Pichu",
	"Cleffa",
	"Igglybuff",
	"Togepi",
	"Togetic",
	"Natu",
	"Xatu",
	"Mareep",
	"Flaaffy",
	"Ampharos",
	"Bellossom",
	"Marill",
	"Azumarill",
	"Sudowoodo",
	"Politoed",
	"Hoppip",
	"Skiploom",
	"Jumpluff",
	"Aipom",
	"Sunkern",
	"Sunflora",
	"Yanma",
	"Wooper",
	"Quagsire",
	"Espeon",
	"Umbreon",
	"Murkrow",
	"Slowking",
	"Misdreavus",
	"Unown",
	"Wobbuffet",
	"Girafarig",
	"Pineco",
	"Forretress",
	"Dunsparce",
	"Gligar",
	"Steelix",
	"Snubbull",
	"Granbull",
	"Qwilfish",
	"Scizor",
	"Shuckle",
	"Heracross",
	"Sneasel",
	"Teddiursa",
	"Ursaring",
	"Slugma",
	"Magcargo",
	"Swinub",
	"Piloswine",
	"Corsola",
	"Remoraid",
	"Octillery",
	"Delibird",
	"Mantine",
	"Skarmory",
	"Houndour",
	"Houndoom",
	"Kingdra",
	"Phanpy",
	"Donphan",
	"Porygon2",
	"Stantler",
	"Smeargle",
	"Tyrogue",
	"Hitmontop",
	"Smoochum",
	"Elekid",
	"Magby",
	"Miltank",
	"Blissey",
	"Raikou",
	"Entei",
	"Suicune",
	"Larvitar",
	"Pupitar",
	"Tyranitar",
	"Lugia",
	"Ho-Oh",
	"Celebi",
	"Treecko",
	"Grovyle",
	"Sceptile",
	"Torchic",
	"Combusken",
	"Blaziken",
	"Mudkip",
	"Marshtomp",
	"Swampert",
	"Poochyena",
	"Mightyena",
	"Zigzagoon",
	"Linoone",
	"Wurmple",
	"Silcoon",
	"Beautifly",
	"Cascoon",
	"Dustox",
	"Lotad",
	"Lombre",
	"Ludicolo",
	"Seedot",
	"Nuzleaf",
	"Shiftry",
	"Taillow",
	"Swellow",
	"Wingull",
	"Pelipper",
	"Ralts",
	"Kirlia",
	"Gardevoir",
	"Surskit",
	"Masquerain",
	"Shroomish",
	"Breloom",
	"Slakoth",
	"Vigoroth",
	"Slaking",
	"Nincada",
	"Ninjask",
	"Shedinja",
	"Whismur",
	"Loudred",
	"Exploud",
	"Makuhita",
	"Hariyama",
	"Azurill",
	"Nosepass",
	"Skitty",
	"Delcatty",
	"Sableye",
	"Mawile",
	"Aron",
	"Lairon",
	"Aggron",
	"Meditite",
	"Medicham",
	"Electrike",
	"Manectric",
	"Plusle",
	"Minun",
	"Volbeat",
	"Illumise",
	"Roselia",
	"Gulpin",
	"Swalot",
	"Carvanha",
	"Sharpedo",
	"Wailmer",
	"Wailord",
	"Numel",
	"Camerupt",
	"Torkoal",
	"Spoink",
	"Grumpig",
	"Spinda",
	"Trapinch",
	"Vibrava",
	"Flygon",
	"Cacnea",
	"Cacturne",
	"Swablu",
	"Altaria",
	"Zangoose",
	"Seviper",
	"Lunatone",
	"Solrock",
	"Barboach",
	"Whiscash",
	"Corphish",
	"Crawdaunt",
	"Baltoy",
	"Claydol",
	"Lileep",
	"Cradily",
	"Anorith",
	"Armaldo",
	"Feebas",
	"Milotic",
	"Castform",
	"Kecleon",
	"Shuppet",
	"Banette",
	"Duskull",
	"Dusclops",
	"Tropius",
	"Chimecho",
	"Absol",
	"Wynaut",
	"Snorunt",
	"Glalie",
	"Spheal",
	"Sealeo",
	"Walrein",
	"Clamperl",
	"Huntail",
	"Gorebyss",
	"Relicanth",
	"Luvdisc",
	"Bagon",
	"Shelgon",
	"Salamence",
	"Beldum",
	"Metang",
	"Metagross",
	"Regirock",
	"Regice",
	"Registeel",
	"Latias",
	"Latios",
	"Kyogre",
	"Groudon",
	"Rayquaza",
	"Jirachi",
	"Deoxys",
	"Turtwig",
	"Grotle",
	"Torterra",
	"Chimchar",
	"Monferno",
	"Infernape",
	"Piplup",
	"Prinplup",
	"Empoleon",
	"Starly",
	"Staravia",
	"Staraptor",
	"Bidoof",
	"Bibarel",
	"Kricketot",
	"Kricketune",
	"Shinx",
	"Luxio",
	"Luxray",
	"Budew",
	"Roserade",
	"Cranidos",
	"Rampardos",
	"Shieldon",
	"Bastiodon",
	"Burmy",
	"Wormadam",
	"Mothim",
	"Combee",
	"Vespiquen",
	"Pachirisu",
	"Buizel",
	"Floatzel",
	"Cherubi",
	"Cherrim",
	"Shellos",
	"Gastrodon",
	"Ambipom",
	"Drifloon",
	"Drifblim",
	"Buneary",
	"Lopunny",
	"Mismagius",
	"Honchkrow",
	"Glameow",
	"Purugly",
	"Chingling",
	"Stunky",
	"Skuntank",
	"Bronzor",
	"Bronzong",
	"Bonsly",
	"Mime Jr.",
	"Happiny",
	"Chatot",
	"Spiritomb",
	"Gible",
	"Gabite",
	"Garchomp",
	"Munchlax",
	"Riolu",
	"Lucario",
	"Hippopotas",
	"Hippowdon",
	"Skorupi",
	"Drapion",
	"Croagunk",
	"Toxicroak",
	"Carnivine",
	"Finneon",
	"Lumineon",
	"Mantyke",
	"Snover",
	"Abomasnow",
	"Weavile",
	"Magnezone",
	"Lickilicky",
	"Rhyperior",
	"Tangrowth",
	"Electivire",
	"Magmortar",
	"Togekiss",
	"Yanmega",
	"Leafeon",
	"Glaceon",
	"Gliscor",
	"Mamoswine",
	"Porygon-Z",
	"Gallade",
	"Probopass",
	"Dusknoir",
	"Froslass",
	"Rotom",
	"Uxie",
	"Mesprit",
	"Azelf",
	"Dialga",
	"Palkia",
	"Heatran",
	"Regigigas",
	"Giratina",
	"Cresselia",
	"Phione",
	"Manaphy",
	"Darkrai",
	"Shaymin",
	"Arceus",
	"Victini",
	"Snivy",
	"Servine",
	"Serperior",
	"Tepig",
	"Pignite",
	"Emboar",
	"Oshawott",
	"Dewott",
	"Samurott",
	"Patrat",
	"Watchog",
	"Lillipup",
	"Herdier",
	"Stoutland",
	"Purrloin",
	"Liepard",
	"Pansage",
	"Simisage",
	"Pansear",
	"Simisear",
	"Panpour",
	"Simipour",
	"Munna",
	"Musharna",
	"Pidove",
	"Tranquill",
	"Unfezant",
	"Blitzle",
	"Zebstrika",
	"Roggenrola",
	"Boldore",
	"Gigalith",
	"Woobat",
	"Swoobat",
	"Drilbur",
	"Excadrill",
	"Audino",
	"Timburr",
	"Gurdurr",
	"Conkeldurr",
	"Tympole",
	"Palpitoad",
	"Seismitoad",
	"Throh",
	"Sawk",
	"Sewaddle",
	"Swadloon",
	"Leavanny",
	"Venipede",
	"Whirlipede",
	"Scolipede",
	"Cottonee",
	"Whimsicott",
	"Petilil",
	"Lilligant",
	"Basculin",
	"Sandile",
	"Krokorok",
	"Krookodile",
	"Darumaka",
	"Darmanitan",
	"Maractus",
	"Dwebble",
	"Crustle",
	"Scraggy",
	"Scrafty",
	"Sigilyph",
	"Yamask",
	"Cofagrigus",
	"Tirtouga",
	"Carracosta",
	"Archen",
	"Archeops",
	"Trubbish",
	"Garbodor",
	"Zorua",
	"Zoroark",
	"Minccino",
	"Cinccino",
	"Gothita",
	"Gothorita",
	"Gothitelle",
	"Solosis",
	"Duosion",
	"Reuniclus",
	"Ducklett",
	"Swanna",
	"Vanillite",
	"Vanillish",
	"Vanilluxe",
	"Deerling",
	"Sawsbuck",
	"Emolga",
	"Karrablast",
	"Escavalier",
	"Foongus",
	"Amoonguss",
	"Frillish",
	"Jellicent",
	"Alomomola",
	"Joltik",
	"Galvantula",
	"Ferroseed",
	"Ferrothorn",
	"Klink",
	"Klang",
	"Klinklang",
	"Tynamo",
	"Eelektrik",
	"Eelektross",
	"Elgyem",
	"Beheeyem",
	"Litwick",
	"Lampent",
	"Chandelure",
	"Axew",
	"Fraxure",
	"Haxorus",
	"Cubchoo",
	"Beartic",
	"Cryogonal",
	"Shelmet",
	"Accelgor",
	"Stunfisk",
	"Mienfoo",
	"Mienshao",
	"Druddigon",
	"Golett",
	"Golurk",
	"Pawniard",
	"Bisharp",
	"Bouffalant",
	"Rufflet",
	"Braviary",
	"Vullaby",
	"Mandibuzz",
	"Heatmor",
	"Durant",
	"Deino",
	"Zweilous",
	"Hydreigon",
	"Larvesta",
	"Volcarona",
	"Cobalion",
	"Terrakion",
	"Virizion",
	"Tornadus",
	"Thundurus",
	"Reshiram",
	"Zekrom",
	"Landorus",
	"Kyurem",
	"Keldeo",
	"Meloetta",
	"Genesect",
	"Chespin",
	"Quilladin",
	"Chesnaught",
	"Fennekin",
	"Braixen",
	"Delphox",
	"Froakie",
	"Frogadier",
	"Greninja",
	"Bunnelby",
	"Diggersby",
	"Fletchling",
	"Fletchinder",
	"Talonflame",
	"Scatterbug",
	"Spewpa",
	"Vivillon",
	"Litleo",
	"Pyroar",
	"Flabébé",
	"Floette",
	"Florges",
	"Skiddo",
	"Gogoat",
	"Pancham",
	"Pangoro",
	"Furfrou",
	"Espurr",
	"Meowstic",
	"Honedge",
	"Doublade",
	"Aegislash",
	"Spritzee",
	"Aromatisse",
	"Swirlix",
	"Slurpuff",
	"Inkay",
	"Malamar",
	"Binacle",
	"Barbaracle",
	"Skrelp",
	"Dragalge",
	"Clauncher",
	"Clawitzer",
	"Helioptile",
	"Heliolisk",
	"Tyrunt",
	"Tyrantrum",
	"Amaura",
	"Aurorus",
	"Sylveon",
	"Hawlucha",
	"Dedenne",
	"Carbink",
	"Goomy",
	"Sliggoo",
	"Goodra",
	"Klefki",
	"Phantump",
	"Trevenant",
	"Pumpkaboo",
	"Gourgeist",
	"Bergmite",
	"Avalugg",
	"Noibat",
	"Noivern",
	"Xerneas",
	"Yveltal",
	"Zygarde",
	"Diancie",
	"Hoopa",
	"Volcanion",
	"Rowlet",
	"Dartrix",
	"Decidueye",
	"Litten",
	"Torracat",
	"Incineroar",
	"Popplio",
	"Brionne",
	"Primarina",
	"Pikipek",
	"Trumbeak",
	"Toucannon",
	"Yungoos",
	"Gumshoos",
	"Grubbin",
	"Charjabug",
	"Vikavolt",
	"Crabrawler",
	"Crabominable",
	"Oricorio",
	"Cutiefly",
	"Ribombee",
	"Rockruff",
	"Lycanroc",
	"Wishiwashi",
	"Mareanie",
	"Toxapex",
	"Mudbray",
	"Mudsdale",
	"Dewpider",
	"Araquanid",
	"Fomantis",
	"Lurantis",
	"Morelull",
	"Shiinotic",
	"Salandit",
	"Salazzle",
	"Stufful",
	"Bewear",
	"Bounsweet",
	"Steenee",
	"Tsareena",
	"Comfey",
	"Oranguru",
	"Passimian",
	"Wimpod",
	"Golisopod",
	"Sandygast",
	"Palossand",
	"Pyukumuku",
	"Type: Null",
	"Silvally",
	"Minior",
	"Komala",
	"Turtonator",
	"Togedemaru",
	"Mimikyu",
	"Bruxish",
	"Drampa",
	"Dhelmise",
	"Jangmo-o",
	"Hakamo-o",
	"Kommo-o",
	"Tapu Koko",
	"Tapu Lele",
	"Tapu Bulu",
	"Tapu Fini",
	"Cosmog",
	"Cosmoem",
	"Solgaleo",
	"Lunala",
	"Nihilego",
	"Buzzwole",
	"Pheromosa",
	"Xurkitree",
	"Celesteela",
	"Kartana",
	"Guzzlord",
	"Necrozma",
	"Magearna",
	"Marshadow",
	"Poipole",
	"Naganadel",
	"Stakataka",
	"Blacephalon",
	"Zeraora",
	"Meltan",
	"Melmetal",
	"Grookey",
	"Thwackey",
	"Rillaboom",
	"Scorbunny",
	"Raboot",
	"Cinderace",
	"Sobble",
	"Drizzile",
	"Inteleon",
	"Skwovet",
	"Greedent",
	"Rookidee",
	"Corvisquire",
	"Corviknight",
	"Blipbug",
	"Dottler",
	"Orbeetle",
	"Nickit",
	"Thievul",
	"Gossifleur",
	"Eldegoss",
	"Wooloo",
	"Dubwool",
	"Chewtle",
	"Drednaw",
	"Yamper",
	"Boltund",
	"Rolycoly",
	"Carkol",
	"Coalossal",
	"Applin",
	"Flapple",
	"Appletun",
	"Silicobra",
	"Sandaconda",
	"Cramorant",
	"Arrokuda",
	"Barraskewda",
	"Toxel",
	"Toxtricity",
	"Sizzlipede",
	"Centiskorch",
	"Clobbopus",
	"Grapploct",
	"Sinistea",
	"Polteageist",
	"Hatenna",
	"Hattrem",
	"Hatterene",
	"Impidimp",
	"Morgrem",
	"Grimmsnarl",
	"Obstagoon",
	"Perrserker",
	"Cursola",
	"Sirfetch'd",
	"Mr. Rime",
	"Runerigus",
	"Milcery",
	"Alcremie",
	"Falinks",
	"Pincurchin",
	"Snom",
	"Frosmoth",
	"Stonjourner",
	"Eiscue",
	"Indeedee",
	"Morpeko",
	"Cufant",
	"Copperajah",
	"Dracozolt",
	"Arctozolt",
	"Dracovish",
	"Arctovish",
	"Duraludon",
	"Dreepy",
	"Drakloak",
	"Dragapult",
	"Zacian",
	"Zamazenta",
	"Eternatus",
	"Kubfu",
	"Urshifu",
	"Zarude",
	"Regieleki",
	"Regidrago",
	"Glastrier",
	"Spectrier",
	"Calyrex",
	"Wyrdeer",
	"Kleavor",
	"Ursaluna",
	"Basculegion",
	"Sneasler",
	"Overqwil",
	"Enamorus",
	"Sprigatito",
	"Floragato",
	"Meowscarada",
	"Fuecoco",
	"Crocalor",
	"Skeledirge",
	"Quaxly",
	"Quaxwell",
	"Quaquaval",
	"Lechonk",
	"Oinkologne",
	"Dudunsparce",
	"Tarountula",
	"Spidops",
	"Nymble",
	"Lokix",
	"Rellor",
	"Rabsca",
	"Greavard",
	"Houndstone",
	"Flittle",
	"Espathra",
	"Farigiraf",
	"Wiglett",
	"Wugtrio",
	"Dondozo",
	"Veluza",
	"Finizen",
	"Palafin",
	"Smoliv",
	"Dolliv",
	"Arboliva",
	"Capsakid",
	"Scovillain",
	"Tadbulb",
	"Bellibolt",
	"Varoom",
	"Revavroom",
	"Orthworm",
	"Tandemaus",
	"Maushold",
	"Cetoddle",
	"Cetitan",
	"Frigibax",
	"Arctibax",
	"Baxcalibur",
	"Tatsugiri",
	"Cyclizar",
	"Pawmi",
	"Pawmo",
	"Pawmot",
	"Wattrel",
	"Kilowattrel",
	"Bombirdier",
	"Squawkabilly",
	"Flamigo",
	"Klawf",
	"Nacli",
	"Naclstack",
	"Garganacl",
	"Glimmet",
	"Glimmora",
	"Shroodle",
	"Grafaiai",
	"Fidough",
	"Dachsbun",
	"Maschiff",
	"Mabosstiff",
	"Bramblin",
	"Brambleghast",
	"Gimmighoul",
	"Gholdengo",
	"Great Tusk",
	"Brute Bonnet",
	"Walking Wake",
	"Sandy Shocks",
	"Scream Tail",
	"Flutter Mane",
	"Slither Wing",
	"Roaring Moon",
	"Iron Treads",
	"Iron Leaves",
	"Iron Moth",
	"Iron Hands",
	"Iron Jugulis",
	"Iron Thorns",
	"Iron Bundle",
	"Iron Valiant",
	"Ting-Lu",
	"Chien-Pao",
	"Wo-Chien",
	"Chi-Yu",
	"Koraidon",
	"Miraidon",
	"Tinkatink",
	"Tinkatuff",
	"Tinkaton",
	"Charcadet",
	"Armarouge",
	"Ceruledge",
	"Toedscool",
	"Toedscruel",
	"Kingambit",
	"Clodsire",
	"Annihilape",
};

static const char* gender_names[] =
{
	"Male",
	"Female",
	"Genderless",
};

static const char* nature_names[] =
{
	"Hardy",
	"Lonely",
	"Brave",
	"Adamant",
	"Naughty",
	"Bold",
	"Docile",
	"Relaxed",
	"Impish",
	"Lax",
	"Timid",
	"Hasty",
	"Serious",
	"Jolly",
	"Naive",
	"Modest",
	"Mild",
	"Quiet",
	"Bashful",
	"Rash",
	"Calm",
	"Gentle",
	"Sassy",
	"Careful",
	"Quirky",
};

static const char* ability_names[] =
{
	"———",
	"Stench",
	"Drizzle",
	"Speed Boost",
	"Battle Armor",
	"Sturdy",
	"Damp",
	"Limber",
	"Sand Veil",
	"Static",
	"Volt Absorb",
	"Water Absorb",
	"Oblivious",
	"Cloud Nine",
	"Compound Eyes",
	"Insomnia",
	"Color Change",
	"Immunity",
	"Flash Fire",
	"Shield Dust",
	"Own Tempo",
	"Suction Cups",
	"Intimidate",
	"Shadow Tag",
	"Rough Skin",
	"Wonder Guard",
	"Levitate",
	"Effect Spore",
	"Synchronize",
	"Clear Body",
	"Natural Cure",
	"Lightning Rod",
	"Serene Grace",
	"Swift Swim",
	"Chlorophyll",
	"Illuminate",
	"Trace",
	"Huge Power",
	"Poison Point",
	"Inner Focus",
	"Magma Armor",
	"Water Veil",
	"Magnet Pull",
	"Soundproof",
	"Rain Dish",
	"Sand Stream",
	"Pressure",
	"Thick Fat",
	"Early Bird",
	"Flame Body",
	"Run Away",
	"Keen Eye",
	"Hyper Cutter",
	"Pickup",
	"Truant",
	"Hustle",
	"Cute Charm",
	"Plus",
	"Minus",
	"Forecast",
	"Sticky Hold",
	"Shed Skin",
	"Guts",
	"Marvel Scale",
	"Liquid Ooze",
	"Overgrow",
	"Blaze",
	"Torrent",
	"Swarm",
	"Rock Head",
	"Drought",
	"Arena Trap",
	"Vital Spirit",
	"White Smoke",
	"Pure Power",
	"Shell Armor",
	"Air Lock",
	"Tangled Feet",
	"Motor Drive",
	"Rivalry",
	"Steadfast",
	"Snow Cloak",
	"Gluttony",
	"Anger Point",
	"Unburden",
	"Heatproof",
	"Simple",
	"Dry Skin",
	"Download",
	"Iron Fist",
	"Poison Heal",
	"Adaptability",
	"Skill Link",
	"Hydration",
	"Solar Power",
	"Quick Feet",
	"Normalize",
	"Sniper",
	"Magic Guard",
	"No Guard",
	"Stall",
	"Technician",
	"Leaf Guard",
	"Klutz",
	"Mold Breaker",
	"Super Luck",
	"Aftermath",
	"Anticipation",
	"Forewarn",
	"Unaware",
	"Tinted Lens",
	"Filter",
	"Slow Start",
	"Scrappy",
	"Storm Drain",
	"Ice Body",
	"Solid Rock",
	"Snow Warning",
	"Honey Gather",
	"Frisk",
	"Reckless",
	"Multitype",
	"Flower Gift",
	"Bad Dreams",
	"Pickpocket",
	"Sheer Force",
	"Contrary",
	"Unnerve",
	"Defiant",
	"Defeatist",
	"Cursed Body",
	"Healer",
	"Friend Guard",
	"Weak Armor",
	"Heavy Metal",
	"Light Metal",
	"Multiscale",
	"Toxic Boost",
	"Flare Boost",
	"Harvest",
	"Telepathy",
	"Moody",
	"Overcoat",
	"Poison Touch",
	"Regenerator",
	"Big Pecks",
	"Sand Rush",
	"Wonder Skin",
	"Analytic",
	"Illusion",
	"Imposter",
	"Infiltrator",
	"Mummy",
	"Moxie",
	"Justified",
	"Rattled",
	"Magic Bounce",
	"Sap Sipper",
	"Prankster",
	"Sand Force",
	"Iron Barbs",
	"Zen Mode",
	"Victory Star",
	"Turboblaze",
	"Teravolt",
	"Aroma Veil",
	"Flower Veil",
	"Cheek Pouch",
	"Protean",
	"Fur Coat",
	"Magician",
	"Bulletproof",
	"Competitive",
	"Strong Jaw",
	"Refrigerate",
	"Sweet Veil",
	"Stance Change",
	"Gale Wings",
	"Mega Launcher",
	"Grass Pelt",
	"Symbiosis",
	"Tough Claws",
	"Pixilate",
	"Gooey",
	"Aerilate",
	"Parental Bond",
	"Dark Aura",
	"Fairy Aura",
	"Aura Break",
	"Primordial Sea",
	"Desolate Land",
	"Delta Stream",
	"Stamina",
	"Wimp Out",
	"Emergency Exit",
	"Water Compaction",
	"Merciless",
	"Shields Down",
	"Stakeout",
	"Water Bubble",
	"Steelworker",
	"Berserk",
	"Slush Rush",
	"Long Reach",
	"Liquid Voice",
	"Triage",
	"Galvanize",
	"Surge Surfer",
	"Schooling",
	"Disguise",
	"Battle Bond",
	"Power Construct",
	"Corrosion",
	"Comatose",
	"Queenly Majesty",
	"Innards Out",
	"Dancer",
	"Battery",
	"Fluffy",
	"Dazzling",
	"Soul-Heart",
	"Tangling Hair",
	"Receiver",
	"Power of Alchemy",
	"Beast Boost",
	"RKS System",
	"Electric Surge",
	"Psychic Surge",
	"Misty Surge",
	"Grassy Surge",
	"Full Metal Body",
	"Shadow Shield",
	"Prism Armor",
	"Neuroforce",
	"Intrepid Sword",
	"Dauntless Shield",
	"Libero",
	"Ball Fetch",
	"Cotton Down",
	"Propeller Tail",
	"Mirror Armor",
	"Gulp Missile",
	"Stalwart",
	"Steam Engine",
	"Punk Rock",
	"Sand Spit",
	"Ice Scales",
	"Ripen",
	"Ice Face",
	"Power Spot",
	"Mimicry",
	"Screen Cleaner",
	"Steely Spirit",
	"Perish Body",
	"Wandering Spirit",
	"Gorilla Tactics",
	"Neutralizing Gas",
	"Pastel Veil",
	"Hunger Switch",
	"Quick Draw",
	"Unseen Fist",
	"Curious Medicine",
	"Transistor",
	"Dragon’s Maw",
	"Chilling Neigh",
	"Grim Neigh",
	"As One",
	"As One",
	"Lingering Aroma",
	"Seed Sower",
	"Thermal Exchange",
	"Anger Shell",
	"Purifying Salt",
	"Well-Baked Body",
	"Wind Rider",
	"Guard Dog",
	"Rocky Payload",
	"Wind Power",
	"Zero to Hero",
	"Commander",
	"Electromorphosis",
	"Protosynthesis",
	"Quark Drive",
	"Good as Gold",
	"Vessel of Ruin",
	"Sword of Ruin",
	"Tablets of Ruin",
	"Beads of Ruin",
	"Orichalcum Pulse",
	"Hadron Engine",
	"Opportunist",
	"Cud Chew",
	"Sharpness",
	"Supreme Overlord",
	"Costar",
	"Toxic Debris",
	"Armor Tail",
	"Earth Eater",
	"Mycelium Might",
};

static const char* move_names[] =
{
	"———",
	"Pound",
	"Karate Chop",
	"Double Slap",
	"Comet Punch",
	"Mega Punch",
	"Pay Day",
	"Fire Punch",
	"Ice Punch",
	"Thunder Punch",
	"Scratch",
	"Vise Grip",
	"Guillotine",
	"Razor Wind",
	"Swords Dance",
	"Cut",
	"Gust",
	"Wing Attack",
	"Whirlwind",
	"Fly",
	"Bind",
	"Slam",
	"Vine Whip",
	"Stomp",
	"Double Kick",
	"Mega Kick",
	"Jump Kick",
	"Rolling Kick",
	"Sand Attack",
	"Headbutt",
	"Horn Attack",
	"Fury Attack",
	"Horn Drill",
	"Tackle",
	"Body Slam",
	"Wrap",
	"Take Down",
	"Thrash",
	"Double-Edge",
	"Tail Whip",
	"Poison Sting",
	"Twineedle",
	"Pin Missile",
	"Leer",
	"Bite",
	"Growl",
	"Roar",
	"Sing",
	"Supersonic",
	"Sonic Boom",
	"Disable",
	"Acid",
	"Ember",
	"Flamethrower",
	"Mist",
	"Water Gun",
	"Hydro Pump",
	"Surf",
	"Ice Beam",
	"Blizzard",
	"Psybeam",
	"Bubble Beam",
	"Aurora Beam",
	"Hyper Beam",
	"Peck",
	"Drill Peck",
	"Submission",
	"Low Kick",
	"Counter",
	"Seismic Toss",
	"Strength",
	"Absorb",
	"Mega Drain",
	"Leech Seed",
	"Growth",
	"Razor Leaf",
	"Solar Beam",
	"Poison Powder",
	"Stun Spore",
	"Sleep Powder",
	"Petal Dance",
	"String Shot",
	"Dragon Rage",
	"Fire Spin",
	"Thunder Shock",
	"Thunderbolt",
	"Thunder Wave",
	"Thunder",
	"Rock Throw",
	"Earthquake",
	"Fissure",
	"Dig",
	"Toxic",
	"Confusion",
	"Psychic",
	"Hypnosis",
	"Meditate",
	"Agility",
	"Quick Attack",
	"Rage",
	"Teleport",
	"Night Shade",
	"Mimic",
	"Screech",
	"Double Team",
	"Recover",
	"Harden",
	"Minimize",
	"Smokescreen",
	"Confuse Ray",
	"Withdraw",
	"Defense Curl",
	"Barrier",
	"Light Screen",
	"Haze",
	"Reflect",
	"Focus Energy",
	"Bide",
	"Metronome",
	"Mirror Move",
	"Self-Destruct",
	"Egg Bomb",
	"Lick",
	"Smog",
	"Sludge",
	"Bone Club",
	"Fire Blast",
	"Waterfall",
	"Clamp",
	"Swift",
	"Skull Bash",
	"Spike Cannon",
	"Constrict",
	"Amnesia",
	"Kinesis",
	"Soft-Boiled",
	"High Jump Kick",
	"Glare",
	"Dream Eater",
	"Poison Gas",
	"Barrage",
	"Leech Life",
	"Lovely Kiss",
	"Sky Attack",
	"Transform",
	"Bubble",
	"Dizzy Punch",
	"Spore",
	"Flash",
	"Psywave",
	"Splash",
	"Acid Armor",
	"Crabhammer",
	"Explosion",
	"Fury Swipes",
	"Bonemerang",
	"Rest",
	"Rock Slide",
	"Hyper Fang",
	"Sharpen",
	"Conversion",
	"Tri Attack",
	"Super Fang",
	"Slash",
	"Substitute",
	"Struggle",
	"Sketch",
	"Triple Kick",
	"Thief",
	"Spider Web",
	"Mind Reader",
	"Nightmare",
	"Flame Wheel",
	"Snore",
	"Curse",
	"Flail",
	"Conversion 2",
	"Aeroblast",
	"Cotton Spore",
	"Reversal",
	"Spite",
	"Powder Snow",
	"Protect",
	"Mach Punch",
	"Scary Face",
	"Feint Attack",
	"Sweet Kiss",
	"Belly Drum",
	"Sludge Bomb",
	"Mud-Slap",
	"Octazooka",
	"Spikes",
	"Zap Cannon",
	"Foresight",
	"Destiny Bond",
	"Perish Song",
	"Icy Wind",
	"Detect",
	"Bone Rush",
	"Lock-On",
	"Outrage",
	"Sandstorm",
	"Giga Drain",
	"Endure",
	"Charm",
	"Rollout",
	"False Swipe",
	"Swagger",
	"Milk Drink",
	"Spark",
	"Fury Cutter",
	"Steel Wing",
	"Mean Look",
	"Attract",
	"Sleep Talk",
	"Heal Bell",
	"Return",
	"Present",
	"Frustration",
	"Safeguard",
	"Pain Split",
	"Sacred Fire",
	"Magnitude",
	"Dynamic Punch",
	"Megahorn",
	"Dragon Breath",
	"Baton Pass",
	"Encore",
	"Pursuit",
	"Rapid Spin",
	"Sweet Scent",
	"Iron Tail",
	"Metal Claw",
	"Vital Throw",
	"Morning Sun",
	"Synthesis",
	"Moonlight",
	"Hidden Power",
	"Cross Chop",
	"Twister",
	"Rain Dance",
	"Sunny Day",
	"Crunch",
	"Mirror Coat",
	"Psych Up",
	"Extreme Speed",
	"Ancient Power",
	"Shadow Ball",
	"Future Sight",
	"Rock Smash",
	"Whirlpool",
	"Beat Up",
	"Fake Out",
	"Uproar",
	"Stockpile",
	"Spit Up",
	"Swallow",
	"Heat Wave",
	"Hail",
	"Torment",
	"Flatter",
	"Will-O-Wisp",
	"Memento",
	"Facade",
	"Focus Punch",
	"Smelling Salts",
	"Follow Me",
	"Nature Power",
	"Charge",
	"Taunt",
	"Helping Hand",
	"Trick",
	"Role Play",
	"Wish",
	"Assist",
	"Ingrain",
	"Superpower",
	"Magic Coat",
	"Recycle",
	"Revenge",
	"Brick Break",
	"Yawn",
	"Knock Off",
	"Endeavor",
	"Eruption",
	"Skill Swap",
	"Imprison",
	"Refresh",
	"Grudge",
	"Snatch",
	"Secret Power",
	"Dive",
	"Arm Thrust",
	"Camouflage",
	"Tail Glow",
	"Luster Purge",
	"Mist Ball",
	"Feather Dance",
	"Teeter Dance",
	"Blaze Kick",
	"Mud Sport",
	"Ice Ball",
	"Needle Arm",
	"Slack Off",
	"Hyper Voice",
	"Poison Fang",
	"Crush Claw",
	"Blast Burn",
	"Hydro Cannon",
	"Meteor Mash",
	"Astonish",
	"Weather Ball",
	"Aromatherapy",
	"Fake Tears",
	"Air Cutter",
	"Overheat",
	"Odor Sleuth",
	"Rock Tomb",
	"Silver Wind",
	"Metal Sound",
	"Grass Whistle",
	"Tickle",
	"Cosmic Power",
	"Water Spout",
	"Signal Beam",
	"Shadow Punch",
	"Extrasensory",
	"Sky Uppercut",
	"Sand Tomb",
	"Sheer Cold",
	"Muddy Water",
	"Bullet Seed",
	"Aerial Ace",
	"Icicle Spear",
	"Iron Defense",
	"Block",
	"Howl",
	"Dragon Claw",
	"Frenzy Plant",
	"Bulk Up",
	"Bounce",
	"Mud Shot",
	"Poison Tail",
	"Covet",
	"Volt Tackle",
	"Magical Leaf",
	"Water Sport",
	"Calm Mind",
	"Leaf Blade",
	"Dragon Dance",
	"Rock Blast",
	"Shock Wave",
	"Water Pulse",
	"Doom Desire",
	"Psycho Boost",
	"Roost",
	"Gravity",
	"Miracle Eye",
	"Wake-Up Slap",
	"Hammer Arm",
	"Gyro Ball",
	"Healing Wish",
	"Brine",
	"Natural Gift",
	"Feint",
	"Pluck",
	"Tailwind",
	"Acupressure",
	"Metal Burst",
	"U-turn",
	"Close Combat",
	"Payback",
	"Assurance",
	"Embargo",
	"Fling",
	"Psycho Shift",
	"Trump Card",
	"Heal Block",
	"Wring Out",
	"Power Trick",
	"Gastro Acid",
	"Lucky Chant",
	"Me First",
	"Copycat",
	"Power Swap",
	"Guard Swap",
	"Punishment",
	"Last Resort",
	"Worry Seed",
	"Sucker Punch",
	"Toxic Spikes",
	"Heart Swap",
	"Aqua Ring",
	"Magnet Rise",
	"Flare Blitz",
	"Force Palm",
	"Aura Sphere",
	"Rock Polish",
	"Poison Jab",
	"Dark Pulse",
	"Night Slash",
	"Aqua Tail",
	"Seed Bomb",
	"Air Slash",
	"X-Scissor",
	"Bug Buzz",
	"Dragon Pulse",
	"Dragon Rush",
	"Power Gem",
	"Drain Punch",
	"Vacuum Wave",
	"Focus Blast",
	"Energy Ball",
	"Brave Bird",
	"Earth Power",
	"Switcheroo",
	"Giga Impact",
	"Nasty Plot",
	"Bullet Punch",
	"Avalanche",
	"Ice Shard",
	"Shadow Claw",
	"Thunder Fang",
	"Ice Fang",
	"Fire Fang",
	"Shadow Sneak",
	"Mud Bomb",
	"Psycho Cut",
	"Zen Headbutt",
	"Mirror Shot",
	"Flash Cannon",
	"Rock Climb",
	"Defog",
	"Trick Room",
	"Draco Meteor",
	"Discharge",
	"Lava Plume",
	"Leaf Storm",
	"Power Whip",
	"Rock Wrecker",
	"Cross Poison",
	"Gunk Shot",
	"Iron Head",
	"Magnet Bomb",
	"Stone Edge",
	"Captivate",
	"Stealth Rock",
	"Grass Knot",
	"Chatter",
	"Judgment",
	"Bug Bite",
	"Charge Beam",
	"Wood Hammer",
	"Aqua Jet",
	"Attack Order",
	"Defend Order",
	"Heal Order",
	"Head Smash",
	"Double Hit",
	"Roar of Time",
	"Spacial Rend",
	"Lunar Dance",
	"Crush Grip",
	"Magma Storm",
	"Dark Void",
	"Seed Flare",
	"Ominous Wind",
	"Shadow Force",
	"Hone Claws",
	"Wide Guard",
	"Guard Split",
	"Power Split",
	"Wonder Room",
	"Psyshock",
	"Venoshock",
	"Autotomize",
	"Rage Powder",
	"Telekinesis",
	"Magic Room",
	"Smack Down",
	"Storm Throw",
	"Flame Burst",
	"Sludge Wave",
	"Quiver Dance",
	"Heavy Slam",
	"Synchronoise",
	"Electro Ball",
	"Soak",
	"Flame Charge",
	"Coil",
	"Low Sweep",
	"Acid Spray",
	"Foul Play",
	"Simple Beam",
	"Entrainment",
	"After You",
	"Round",
	"Echoed Voice",
	"Chip Away",
	"Clear Smog",
	"Stored Power",
	"Quick Guard",
	"Ally Switch",
	"Scald",
	"Shell Smash",
	"Heal Pulse",
	"Hex",
	"Sky Drop",
	"Shift Gear",
	"Circle Throw",
	"Incinerate",
	"Quash",
	"Acrobatics",
	"Reflect Type",
	"Retaliate",
	"Final Gambit",
	"Bestow",
	"Inferno",
	"Water Pledge",
	"Fire Pledge",
	"Grass Pledge",
	"Volt Switch",
	"Struggle Bug",
	"Bulldoze",
	"Frost Breath",
	"Dragon Tail",
	"Work Up",
	"Electroweb",
	"Wild Charge",
	"Drill Run",
	"Dual Chop",
	"Heart Stamp",
	"Horn Leech",
	"Sacred Sword",
	"Razor Shell",
	"Heat Crash",
	"Leaf Tornado",
	"Steamroller",
	"Cotton Guard",
	"Night Daze",
	"Psystrike",
	"Tail Slap",
	"Hurricane",
	"Head Charge",
	"Gear Grind",
	"Searing Shot",
	"Techno Blast",
	"Relic Song",
	"Secret Sword",
	"Glaciate",
	"Bolt Strike",
	"Blue Flare",
	"Fiery Dance",
	"Freeze Shock",
	"Ice Burn",
	"Snarl",
	"Icicle Crash",
	"V-create",
	"Fusion Flare",
	"Fusion Bolt",
	"Flying Press",
	"Mat Block",
	"Belch",
	"Rototiller",
	"Sticky Web",
	"Fell Stinger",
	"Phantom Force",
	"Trick-or-Treat",
	"Noble Roar",
	"Ion Deluge",
	"Parabolic Charge",
	"Forest’s Curse",
	"Petal Blizzard",
	"Freeze-Dry",
	"Disarming Voice",
	"Parting Shot",
	"Topsy-Turvy",
	"Draining Kiss",
	"Crafty Shield",
	"Flower Shield",
	"Grassy Terrain",
	"Misty Terrain",
	"Electrify",
	"Play Rough",
	"Fairy Wind",
	"Moonblast",
	"Boomburst",
	"Fairy Lock",
	"King’s Shield",
	"Play Nice",
	"Confide",
	"Diamond Storm",
	"Steam Eruption",
	"Hyperspace Hole",
	"Water Shuriken",
	"Mystical Fire",
	"Spiky Shield",
	"Aromatic Mist",
	"Eerie Impulse",
	"Venom Drench",
	"Powder",
	"Geomancy",
	"Magnetic Flux",
	"Happy Hour",
	"Electric Terrain",
	"Dazzling Gleam",
	"Celebrate",
	"Hold Hands",
	"Baby-Doll Eyes",
	"Nuzzle",
	"Hold Back",
	"Infestation",
	"Power-Up Punch",
	"Oblivion Wing",
	"Thousand Arrows",
	"Thousand Waves",
	"Land’s Wrath",
	"Light of Ruin",
	"Origin Pulse",
	"Precipice Blades",
	"Dragon Ascent",
	"Hyperspace Fury",
	"Breakneck Blitz",
	"Breakneck Blitz",
	"All-Out Pummeling",
	"All-Out Pummeling",
	"Supersonic Skystrike",
	"Supersonic Skystrike",
	"Acid Downpour",
	"Acid Downpour",
	"Tectonic Rage",
	"Tectonic Rage",
	"Continental Crush",
	"Continental Crush",
	"Savage Spin-Out",
	"Savage Spin-Out",
	"Never-Ending Nightmare",
	"Never-Ending Nightmare",
	"Corkscrew Crash",
	"Corkscrew Crash",
	"Inferno Overdrive",
	"Inferno Overdrive",
	"Hydro Vortex",
	"Hydro Vortex",
	"Bloom Doom",
	"Bloom Doom",
	"Gigavolt Havoc",
	"Gigavolt Havoc",
	"Shattered Psyche",
	"Shattered Psyche",
	"Subzero Slammer",
	"Subzero Slammer",
	"Devastating Drake",
	"Devastating Drake",
	"Black Hole Eclipse",
	"Black Hole Eclipse",
	"Twinkle Tackle",
	"Twinkle Tackle",
	"Catastropika",
	"Shore Up",
	"First Impression",
	"Baneful Bunker",
	"Spirit Shackle",
	"Darkest Lariat",
	"Sparkling Aria",
	"Ice Hammer",
	"Floral Healing",
	"High Horsepower",
	"Strength Sap",
	"Solar Blade",
	"Leafage",
	"Spotlight",
	"Toxic Thread",
	"Laser Focus",
	"Gear Up",
	"Throat Chop",
	"Pollen Puff",
	"Anchor Shot",
	"Psychic Terrain",
	"Lunge",
	"Fire Lash",
	"Power Trip",
	"Burn Up",
	"Speed Swap",
	"Smart Strike",
	"Purify",
	"Revelation Dance",
	"Core Enforcer",
	"Trop Kick",
	"Instruct",
	"Beak Blast",
	"Clanging Scales",
	"Dragon Hammer",
	"Brutal Swing",
	"Aurora Veil",
	"Sinister Arrow Raid",
	"Malicious Moonsault",
	"Oceanic Operetta",
	"Guardian of Alola",
	"Soul-Stealing 7-Star Strike",
	"Stoked Sparksurfer",
	"Pulverizing Pancake",
	"Extreme Evoboost",
	"Genesis Supernova",
	"Shell Trap",
	"Fleur Cannon",
	"Psychic Fangs",
	"Stomping Tantrum",
	"Shadow Bone",
	"Accelerock",
	"Liquidation",
	"Prismatic Laser",
	"Spectral Thief",
	"Sunsteel Strike",
	"Moongeist Beam",
	"Tearful Look",
	"Zing Zap",
	"Nature’s Madness",
	"Multi-Attack",
	"10,000,000 Volt Thunderbolt",
	"Mind Blown",
	"Plasma Fists",
	"Photon Geyser",
	"Light That Burns the Sky",
	"Searing Sunraze Smash",
	"Menacing Moonraze Maelstrom",
	"Let’s Snuggle Forever",
	"Splintered Stormshards",
	"Clangorous Soulblaze",
	"Zippy Zap",
	"Splishy Splash",
	"Floaty Fall",
	"Pika Papow",
	"Bouncy Bubble",
	"Buzzy Buzz",
	"Sizzly Slide",
	"Glitzy Glow",
	"Baddy Bad",
	"Sappy Seed",
	"Freezy Frost",
	"Sparkly Swirl",
	"Veevee Volley",
	"Double Iron Bash",
	"Max Guard",
	"Dynamax Cannon",
	"Snipe Shot",
	"Jaw Lock",
	"Stuff Cheeks",
	"No Retreat",
	"Tar Shot",
	"Magic Powder",
	"Dragon Darts",
	"Teatime",
	"Octolock",
	"Bolt Beak",
	"Fishious Rend",
	"Court Change",
	"Max Flare",
	"Max Flutterby",
	"Max Lightning",
	"Max Strike",
	"Max Knuckle",
	"Max Phantasm",
	"Max Hailstorm",
	"Max Ooze",
	"Max Geyser",
	"Max Airstream",
	"Max Starfall",
	"Max Wyrmwind",
	"Max Mindstorm",
	"Max Rockfall",
	"Max Quake",
	"Max Darkness",
	"Max Overgrowth",
	"Max Steelspike",
	"Clangorous Soul",
	"Body Press",
	"Decorate",
	"Drum Beating",
	"Snap Trap",
	"Pyro Ball",
	"Behemoth Blade",
	"Behemoth Bash",
	"Aura Wheel",
	"Breaking Swipe",
	"Branch Poke",
	"Overdrive",
	"Apple Acid",
	"Grav Apple",
	"Spirit Break",
	"Strange Steam",
	"Life Dew",
	"Obstruct",
	"False Surrender",
	"Meteor Assault",
	"Eternabeam",
	"Steel Beam",
	"Expanding Force",
	"Steel Roller",
	"Scale Shot",
	"Meteor Beam",
	"Shell Side Arm",
	"Misty Explosion",
	"Grassy Glide",
	"Rising Voltage",
	"Terrain Pulse",
	"Skitter Smack",
	"Burning Jealousy",
	"Lash Out",
	"Poltergeist",
	"Corrosive Gas",
	"Coaching",
	"Flip Turn",
	"Triple Axel",
	"Dual Wingbeat",
	"Scorching Sands",
	"Jungle Healing",
	"Wicked Blow",
	"Surging Strikes",
	"Thunder Cage",
	"Dragon Energy",
	"Freezing Glare",
	"Fiery Wrath",
	"Thunderous Kick",
	"Glacial Lance",
	"Astral Barrage",
	"Eerie Spell",
	"Dire Claw",
	"Psyshield Bash",
	"Power Shift",
	"Stone Axe",
	"Springtide Storm",
	"Mystical Power",
	"Raging Fury",
	"Wave Crash",
	"Chloroblast",
	"Mountain Gale",
	"Victory Dance",
	"Headlong Rush",
	"Barb Barrage",
	"Esper Wing",
	"Bitter Malice",
	"Shelter",
	"Triple Arrows",
	"Infernal Parade",
	"Ceaseless Edge",
	"Bleakwind Storm",
	"Wildbolt Storm",
	"Sandsear Storm",
	"Lunar Blessing",
	"Take Heart",
	"Tera Blast",
	"Silk Trap",
	"Axe Kick",
	"Last Respects",
	"Lumina Crash",
	"Order Up",
	"Jet Punch",
	"Spicy Extract",
	"Spin Out",
	"Population Bomb",
	"Ice Spinner",
	"Glaive Rush",
	"Revival Blessing",
	"Salt Cure",
	"Triple Dive",
	"Mortal Spin",
	"Doodle",
	"Fillet Away",
	"Kowtow Cleave",
	"Flower Trick",
	"Torch Song",
	"Aqua Step",
	"Raging Bull",
	"Make It Rain",
	"Psyblade",
	"Hydro Steam",
	"Ruination",
	"Collision Course",
	"Electro Drift",
	"Shed Tail",
	"Chilly Reception",
	"Tidy Up",
	"Snowscape",
	"Pounce",
	"Trailblaze",
	"Chilling Water",
	"Hyper Drill",
	"Twin Beam",
	"Rage Fist",
	"Armor Cannon",
	"Bitter Blade",
	"Double Shock",
	"Gigaton Hammer",
	"Comeuppance",
	"Aqua Cutter",
	"Blazing Torque",
	"Wicked Torque",
	"Noxious Torque",
	"Combat Torque",
	"Magical Torque",
};

static const char* type_names[] =
{
	"Normal",
	"Fighting",
	"Flying",
	"Poison",
	"Ground",
	"Rock",
	"Bug",
	"Ghost",
	"Steel",
	"Fire",
	"Water",
	"Grass",
	"Electric",
	"Psychic",
	"Ice",
	"Dragon",
	"Dark",
	"Fairy",
};

static const char* stage_names_story[] =
{
	"None",
	"3* unlocked",
	"4* unlocked",
	"5* unlocked",
	"6* unlocked",
};

static const char* stage_names_event[] =
{
	"2* unlocked",
	"3* unlocked",
	"4* unlocked",
	"7* unlocked",
};
